Ojemba website project
kaitcham/ojemba pull request #20
Opened 2023-08-30 20:42 UTC by kaitcham

## Ojemba website project

### In this pull request we have
- [x] Implemented this [Figma](https://www.figma.com/file/YRF8ZXuCSDqwmBI9iurvVC/Ojemba.de-VLM-(Copy)?type=design&node-id=58-2&mode=design&t=YxEdAJ7PNmozZNUh-0) design
- [x] Performed a self-review of our code
- [x] Implemented both mobile and desktop design

## Deployed version
[Ojemba website project](https://kaitcham-ojemba-project.netlify.app/)

## Built With
- HTML
- Tailwind CSS
- JavaScript

## Getting Started
### Install

- [Git](https://git-scm.com/downloads)
- [Node](https://nodejs.org/en/download/)
- Clone the repository
  - ```
    git clone https://github.com/kaitcham/ojemba
    ```

- Navigate to the project's root folder:
  - ```
    cd ojemba
    ```

- Install dependencies:
  - ```
    npm install
    ```
- Start project:
  - ```
    npm start
    ```

## Authors

👤 **Munezero Christian**

- GitHub: [@kaitcham](https://github.com/kaitcham)
- Twitter: [@kaitcham](https://twitter.com/kaitcham)
- LinkedIn: [@kaitcham](https://www.linkedin.com/in/kaitcham/)

2023-08-31 09:52 UTC, Yvad60 requested changes
Good job team, I noticed a lot of cool changes that you implemented in the current pull request, I left some comments about few suggestion about how to make it better

2023-08-31 09:52 UTC, Yvad60 commented on tailwind.config.js
> +        third: "#0000",
I think this Hex color code here is not valid, it may probably work in the browser but a valid CSS Hex color code has to be at least 3 or 6 in length. If you were going for the black color `#000` or `#000000` would be a better choice. 

Also `third` as the color name is descriptive enough to explain the nature of the color or where you may use it, you can find a better name

2023-08-31 09:52 UTC, Yvad60 commented on package.json
> +    "start": "npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch"
The `watch` and `start` scripts match (are doing the same thing). Either one of them is not correct or you don't need both of them

2023-08-31 09:52 UTC, Yvad60 commented on index.html
> +  </head>
You can also include the `<title>` tag to define the document title. The title tag plays a role in the Search engine optimization (SEO) and accessibility of the webpage so it is a good practice to add it at least on the main webpage. Since you were not given the exact content to put there it's up to you to decide the title to use.

2023-08-31 09:52 UTC, Yvad60 commented on src/assets/Africa.png
You also have the `svg` version of the same image you can keep the one you need and remove the other

2023-08-31 09:52 UTC, Yvad60 commented on src/sections/our-teams.html
> +          <img src="./src/assets/Pictures.png" alt="" class="h-full w-full object-cover sm:hidden" />
I noticed that you have used element selectors like `[&>div]`, `[&_h4]`, `[&_p]` in different places to combine multiple elements styles in one element. When working with Tailwind CSS, especially in a team project this may have two disadvantages

- Since you didn't use this system consistently in all places someone may be confused that an element is not styled because it has no class attribute and yet it was targeted and styled in the parent element therefore it may be hard to debug especially for someone who didn't write the code since they had to check different places to see where the element was styled from .

- When you have a class like `[&_p]:italic` in your output CSS file tailwind will build a separate class that may look like the following 
```css
.\[\&_p\]\:italic p{
  font-style: italic;
}
```
and if you have used `italic` class somewhere separately, Tailwind will also build it as a separate class and they are both doing the same thing 
The more you use an element selector you may be unnecessarily recreating classes that may already exist in your output CSS  file and this may make your CSS file huge and affect the performance of your website

This is just optional and more like a personal opinion so you don't have to implement it if you don't want to or don't have enough time, but in most cases, you should prioritize making code easy to read some solutions are not worth the struggle that the reader of your code may go through trying to understand what's happening

2023-08-31 09:52 UTC, Yvad60 commented on src/assets/.svg
I think the name of this file is a bit confusing 🙂

2023-08-31 09:52 UTC, Yvad60 commented on src/scripts/main.js
> +}
Good job on implementing this👌

2023-08-31 09:52 UTC, Yvad60 commented on src/scripts/main.js
> +  if (event.target.nodeName === "SPAN") {
Why do you need to check that the element is a `span`

2023-08-31 13:01 UTC, Algor-Fernand commented on index.html
> +  </head>
Thanks for the feedback, we had missed that issue. We're resolving this right away...

2023-08-31 13:05 UTC, Yvad60 requested changes

2023-08-31 13:05 UTC, Yvad60 commented on src/assets/video.webp
You are probably not using this image anymore (since you are now using the iframe) same as the other video image

2023-08-31 13:05 UTC, Yvad60 commented on src/sections/footer.html
> +          alt="Ojemba's logo"
Great job on adding the alt text on this image. I noticed that on most images you only have an empty string.

2023-08-31 13:05 UTC, Yvad60 commented on src/sections/our-teams.html
> +        <iframe class="h-[220px] md:h-[760px] w-full rounded-sm"
Here you are mixing CSS units (`rem` and `pixels`). It is important that you have a consistent system and that you strictly stick to it. For instance, if you choose to use `rems` you use them everywhere. But also if you want to use Pixels you use them everywhere without mixing them.

2023-08-31 13:05 UTC, Yvad60 commented on src/sections/hero.html
> +          <li>EN</li>
I noticed that there are a few places where you have some elements with an empty class attribute like you are already doing If you are not styling the element you should remove the class attribute.

By the way, these kinds of comments may seem less important since the app can still work just fine with empty classes, but to some people, these small things may be a sign that the author of the code was not careful enough or the feature was not thoroughly reviewed

2023-08-31 13:05 UTC, Yvad60 commented on src/assets/Ojembees.png
I think you need to make changes to the way you use assets, as we agreed in one of our meetings we decided to use the `.webp` format for images and `.svg` for icons. I noticed that you are using `webp` but there are also a few `pngs` in the codebase


One thing to add to this is to ensure that the assets files have descriptive names that can describe the file.  Sometimes when you export an asset from Figma the name is not always descriptive enough 

Also, another folder structure good practice in case you have many assets is to split your assets into different small folders where in the `assets` folder you may have small folders like `images`, `icons`, `fonts`...

2023-08-31 13:12 UTC, uwumukiza123 commented on tailwind.config.js
> +        third: "#0000",
Thank you,  we have have fixed this issue

2023-08-31 16:51 UTC, Algor-Fernand commented on src/sections/hero.html
> +          <li>EN</li>
This is fixed

2023-08-31 17:07 UTC, uwumukiza123 commented on src/assets/Ojembees.png
Thank you for mentioning this, we did not even notice them before, we have now removed unnecessary things and the assets are in the the right folder according to the type and we used images in .webp format but left icons in PNG format

2023-09-01 11:14 UTC, Yvad60 requested changes

2023-09-01 11:14 UTC, Yvad60 commented on src/assets/images/Objekt 9 1.webp
Some assets are still not well named.

2023-09-01 11:14 UTC, Yvad60 commented on src/sections/our-teams.html
> +        Entwickler:innen zusammen. Alle Entwickler:innern besitzen bei uns das
You probably missed this one `max-w-[820px]`

2023-09-01 16:49 UTC, Yvad60 approved these changes
Hi team I am really happy with the good work you have done and the changes you have implemented. I am approving The PR 
Good job🌟🌟🌟.

2023-09-08 06:42 UTC, merged