add advantages section
kaitcham/ojemba pull request #4
Opened 2023-08-21 14:12 UTC by uwumukiza123

## Changes

- [x] I have worked on advantages section
- [x] my code follows the style guidelines of this project
- [x] I have performed a self-review of my code

2023-08-21 18:08 UTC, Algor-Fernand requested changes
Heyy @uwumukiza123, It seems there are conflicts. I'd suggest adding scripts in the provided main.js in the script directory.

2023-08-21 18:08 UTC, Algor-Fernand commented on src/sections/advantages.html
Hello @uwumukiza123, in general everything looks good to me. However, I'd suggest removing the blank space between lines like line 2, line 5, and so on. Also on line 3 remember to remove arbitrary values since they are already in the tailwind config of this project.

2023-08-22 10:11 UTC, Algor-Fernand approved these changes

2023-08-22 15:40 UTC, kaitcham approved these changes
Hello @uwumukiza123

Excellent work!  💯
You have done a great job and there is nothing else to say other than... it's time to merge it.

Happy coding!!! 👯

2023-08-22 15:41 UTC, merged